{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "764960d5-d045-4837-9fc9-9e622730ff71",
   "metadata": {},
   "outputs": [],
   "source": [
    "# %%\n",
    "# # Streamlit App for Bucknell Reunion Attendance Prediction\n",
    "# ### Uses a trained ML model saved as a pickle file\n",
    "\n",
    "# %%\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import pickle\n",
    "\n",
    "# Load trained model\n",
    "file_to_load = 'xgboost_reunion_model.pkl'   # <-- CHANGE to your actual model file\n",
    "with open(file_to_load, 'rb') as file:\n",
    "    loaded_model = pickle.load(file)\n",
    "\n",
    "# ------------------- UI LAYOUT -------------------\n",
    "st.set_page_config(page_title=\"🎓 Reunion Attendance Predictor\", layout=\"centered\")\n",
    "st.title(\"🎓 Alumni Reunion Attendance Predictor\")\n",
    "st.markdown(\"Enter alumni information below to estimate the probability of attending.\")\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "# ------------------- USER INPUTS -------------------\n",
    "\n",
    "bucknell_year = st.slider(\"Bucknell Class Year\", 1950, 2025, 2000)\n",
    "\n",
    "peer_to_peer = st.checkbox(\"Peer-to-Peer Invite?\")\n",
    "prospect = st.checkbox(\"Prospect\")\n",
    "greek_sorority = st.checkbox(\"Greek Life – Sorority\")\n",
    "volunteer = st.checkbox(\"Volunteer\")\n",
    "donor = st.checkbox(\"Donor\")\n",
    "\n",
    "cornerstone_potential = st.checkbox(\"Cornerstone Status: Potential Renew\")\n",
    "cornerstone_renew = st.checkbox(\"Cornerstone Status: Renew\")\n",
    "\n",
    "event_info = st.checkbox(\"Received Event Information?\")\n",
    "\n",
    "num_volunteer_activities = st.slider(\n",
    "    \"Number of Volunteer Activities\",\n",
    "    min_value=0,\n",
    "    max_value=50,\n",
    "    value=0\n",
    ")\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "# ------------------- PREDICTION -------------------\n",
    "\n",
    "if st.button(\"Predict Attendance\"):\n",
    "\n",
    "    # Create input dataframe EXACTLY matching model features\n",
    "    new_alumni = pd.DataFrame({\n",
    "        'Bucknell_Class_Year': [bucknell_year],\n",
    "        'Peer-to-Peer': [int(peer_to_peer)],\n",
    "        'Prospect': [int(prospect)],\n",
    "        'Greek_Type_Sorority': [int(greek_sorority)],\n",
    "        'Cornerstone_Status_POTENTIAL RENEW CS': [int(cornerstone_potential)],\n",
    "        'Volunteer': [int(volunteer)],\n",
    "        'Event_Information': [int(event_info)],\n",
    "        'Cornerstone_Status_RENEW CS': [int(cornerstone_renew)],\n",
    "        'Number_Volunteer_Activities': [num_volunteer_activities],\n",
    "        'Donor': [int(donor)]\n",
    "    })\n",
    "\n",
    "    # Predict probability\n",
    "    predicted_prob = loaded_model.predict_proba(new_alumni)[:, 1]\n",
    "    predicted_class = loaded_model.predict(new_alumni)\n",
    "\n",
    "    formatted_prob = f\"{predicted_prob[0]:.2f}\"\n",
    "\n",
    "    st.markdown(\"## ✅ Prediction Results\")\n",
    "    st.write(f\"**Predicted Probability of Attending:** {formatted_prob}\")\n",
    "\n",
    "    if predicted_class[0] == 1:\n",
    "        st.success(\"🎉 Predicted Outcome: **Will Attend**\")\n",
    "    else:\n",
    "        st.error(\"❌ Predicted Outcome: **Will Not Attend**\")\n",
    "\n",
    "    # ------------------- VISUAL BREAKDOWN -------------------\n",
    "\n",
    "    probabilities = [1 - predicted_prob[0], predicted_prob[0]]\n",
    "    labels = ['Will Not Attend', 'Will Attend']\n",
    "\n",
    "    chart_data = pd.DataFrame({'Probability': probabilities}, index=labels)\n",
    "\n",
    "    st.markdown(\"### 📊 Prediction Breakdown\")\n",
    "    st.bar_chart(chart_data)\n",
    "\n",
    "st.markdown(\"---\")\n",
    "st.markdown(\"**Bucknell Reunion Attendance ML App** | Powered by Streamlit\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
